config/routes.rb
Nyweb::Application.routes.draw do
  get "password_resets/new"

  get "password_resets/edit"

  get "password_resets/update"

  resources :image_groups

  resources :images
  resources :comments, :only => [:create, :destroy, :show]

  resources :users#, :only => [:show, :update,:edit]
  resources :sessions, :only => [:new, :create, :destroy]
  resources :messages, :only => [:index, :new, :create, :show, :destroy]
  resources :password_resets

  get "pub/index"

  root to: 'pub#index'  
  match "/about" => "pub#about"
  match "/contact" => "pub#contact"
  match "/recruit" => "pub#recruit"
  match "/ba" => "pub#ba"
  match "/signout" => "sessions#destroy"
  match "/education" => "pub#edu"
  match "/cate" => "pub#cate"
  match "/fab" => "pub#fab"
  match "/tour" => "pub#tour"
  match "/beauty" => "pub#beauty"
  match "/entertainment" => "pub#entertainment"
  match "/show" => "pub#show"
  match "/decoration" => "pub#decoration"
  match "/promotion" => "pub#promotion"

  match "/slide_modal/:id" => "pub#showSlideModal"
  match "/slide_modal" => "pub#showSlideModalFake"

  match "/update_password" => "users#updatePWD"
  match "/update_email" => "users#updateEmail"
  match "/update_address" => "users#updateAddress"
  match "/update_phone" => "users#updatePhone"

  match "/admin" => "admin#index"
  match "/image_select" => "image_groups#image_select"
  match "/gravatar" => "pub#gravatar"

  match "*a" => "pub#render_404"

end

app/models/image_group.rb
class ImageGroup < ActiveRecord::Base
  attr_accessible :category_id, :cover_image_id, :desc, :enabled, :group_name, :key_word, :weight_factor, :promoted
  has_many :images, foreign_key: "group_id"
  belongs_to :cover, class_name: "Image", foreign_key: "cover_image_id"
  belongs_to :category
  paginates_per 3

  validates :group_name, presence: {message: "组名不能为空"}
  validates :weight_factor, presence: {message: "权重不能为空"}
end

app/controllers/image_groups_controller.rb
class ImageGroupsController < ApplicationController
  # GET /image_groups
  # GET /image_groups.json
  def index
    @category_id = params[:category_id]
    page = params[:page]
    if @category_id == nil
    	@category_id = 1
    end
    
    @image_groups = ImageGroup.order("weight_factor asc").where(" category_id = '#{@category_id}'").page(page)
  end

  # GET /image_groups/1
  # GET /image_groups/1.json
  def show
    @image_group = ImageGroup.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @image_group }
    end
  end

  # GET /image_groups/new
  # GET /image_groups/new.json
  def new
    @image_group = ImageGroup.new
    @category_id = params[:category_id]
    puts ">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>"
    puts "xxxx" unless  !@image_group.id.nil? 
    puts ">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>"
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @image_group }
      #format.js { render js:"$('#subpage-pane').html('<%= j render :partial=>form %>')" }
      format.js {}
    end
  end

  # GET /image_groups/1/edit
  def edit
    @image_group = ImageGroup.find(params[:id])
  end

  # POST /image_groups
  # POST /image_groups.json
  def create
    @image_group = ImageGroup.new(params[:image_group])
    puts params[:image_group]
    puts params[:image_group][:enabled]
    
    
    respond_to do |format|
      if @image_group.save
        format.html { redirect_to @image_group, notice: 'Image group was successfully created.' }
        format.json { render json: @image_group, status: :created, location: @image_group }
        format.js
      else
        format.html { render action: "new" }
        format.json { render json: @image_group.errors, status: :unprocessable_entity }
        format.js
      end
    end

    p @image_group.errors.full_messages
  end

  # PUT /image_groups/1
  # PUT /image_groups/1.json
  def update
    puts params[:image_group]
    puts params[:image_group][:promoted]
    p ">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>"
    if !params[:images][:removed].blank?
      puts "removed images" + params[:images][:removed]
      removedImages = Image.where(" id in (?)", params[:images][:removed].split(','))

      #remove the image from a group
      removedImages.each do |ri|
        ri.group_id=nil
        ri.save
      end
    end

    if !params[:images][:added].blank?
      puts "new added images" + params[:images][:added]
      addedImages = Image.where(" id in (?)", params[:images][:added].split(','))

      #remove the image from a group
      addedImages.each do |ai|
        ai.group_id=params[:id]
        ai.save
      end
    end    


    @image_group = ImageGroup.find(params[:id])

    if params[:image_group][:cover_image_id].nil?
      @image_group.errors.add(:nil_cover, "必须指定封面图片才能使该图组生效")
      return
    elsif @image_group.images.nil?
      @image_group.errors.add(:nil_images, "必须指定内容图片才能使该图组生效")
      return    
    end

    respond_to do |format|
      if @image_group.update_attributes(params[:image_group])
        format.html { redirect_to @image_group, notice: 'Image group was successfully updated.' }
        format.json { head :no_content }
        format.js {}
      else
        format.html { render action: "edit" }
        format.json { render json: @image_group.errors, status: :unprocessable_entity }
        format.js {}
      end
    end
  end

  # DELETE /image_groups/1
  # DELETE /image_groups/1.json
  def destroy
    @image_group = ImageGroup.find(params[:id])
    @image_group.destroy

    respond_to do |format|
      format.html { redirect_to image_groups_url }
      format.json { head :no_content }
      format.js {}
    end
  end

  def image_select
   group_id = params[:group_id]
   @group = ImageGroup.find_by_id(params[:group_id])

   @contentSelection = params[:content]

   @images = @group.images.page(1)

   if params[:content] == "true"
    @available_images = Image.where(" enabled = true and (group_id is null or group_id = '')").page(1)
  end
  puts @available_images
end
end

app/helpers/image_groups_helper.rb
module ImageGroupsHelper
end

app/views/image_groups/_form.html.erb
<%= form_for(@image_group, remote:true, html: { class:"form-horizontal" } ) do |f| %>
<% if @image_group.errors.any? %>
<div id="error_explanation" class="alert alert-error">
  <ul>
    <% @image_group.errors.each do |attribute, msg| %>
    <li><%= msg %></li>
    <% end %>
  </ul>
</div>
<% end %>

<div id="control-group-group_name" class="field control-group">
  <%= f.label "图组名", class:"control-label" %>
  <div class="controls">
    <%= f.text_field :group_name %>
  </div>
</div>
<div id="control-group-category_id" class="field control-group">
  <%= f.label "所属分类", class:"control-label" %>
  <div class="controls">
    <%= f.select :category_id,  Category.all.collect {|c| [ c.name, c.id ] }, { selected: (@image_group.category_id.nil?) ?  category_id : @image_group.category_id  } %>
  </div>
</div>
<div id="control-group-key_word" class="field control-group">
  <%= f.label "关键字", class:"control-label" %>
  <div class="controls">
    <%= f.text_field :key_word %>
  </div>
</div>
<div id="control-group-desc" class="field control-group">
  <%= f.label "描述", class:"control-label" %>
  <div class="controls">
    <%= f.text_field :desc %>
  </div>
</div>
<div id="control-group-weight_factor" class="field control-group">
  <%= f.label "权重", class:"control-label" %>
  <div class="controls">
    <%= f.number_field :weight_factor %>
  </div>
</div>

<% if !@image_group.id.nil? %>
<div class="field control-group">
  <%= f.label "封面图选择", class:"control-label" %>
  <div class="controls">
    <%= f.hidden_field :cover_image_id %>
    <span id="cover_image">
      <% if !@image_group.cover_image_id.nil? %>
        <%= image_tag (@image_group.cover.instance.url || @image_group.cover.location), size:"100x50" %>
      <% end  %>
    </span>
    <%= link_to "选择", image_select_path(group_id:@image_group.id), remote:true, class:"btn btn-link" %>
  </div>
</div>
<div class="field control-group">
  <%= f.label "内容图选择", class:"control-label" %>
  <div class="controls">
    <%= hidden_field "images", "removed" %>
    <%= hidden_field "images", "added" %>
    <span id="content_image">
      <% @image_group.images.each do |image| %>
        <%= image_tag (image.instance.url || image.location), size:"100x50" %>
      <% end  %>
    </span>
    <%= link_to "选择", image_select_path(group_id:@image_group.id, content:true), remote:true, class:"btn btn-link", 'data-toggle'=>"modal" %>
  </div>
</div>
<% end  %>

<div class="field control-group">
  <div class="controls">
    <%= f.check_box :enabled, { disabled: (true unless !@image_group.id.nil?) }, checked_value = "true", unchecked_value = "false" %>
    <span>&nbsp;&nbsp;&nbsp;使之生效</span>
    <strong class="text-error"><abbr title="只能在为该图组选择好图片并且指定封面后才能被置为 生效 状态"> *</abbr></strong>
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    <%= f.check_box :promoted, { disabled: (true unless !@image_group.id.nil?) }, checked_value = "true", unchecked_value = "false" %>
    <span>&nbsp;&nbsp;&nbsp;首页展示</span>
  </div>
</div>
<div class="actions control-group">
  <div class="controls">
    <%= f.submit "提交", remote:true, class:"btn btn-warning"  %>
    <button id="ig_form_rtn" type="button" class="btn btn-default">返回</button>
  </div>
</div>
<% end %>


<!-- Modal -->
<div id="select_img_modal" class="advanced-modal hide fade" role="dialog" aria-labelledby="imgModal" aria-hidden="true">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
    <h3  id="imgModal">选择图片</h3>
  </div>
  <div id="modal_body" class="modal-body">
  </div>
  <div class="modal-footer">
    <button id="btn_confirm" class="btn btn-primary">确认</button>
    <button class="btn" data-dismiss="modal" aria-hidden="true">关闭</button>
  </div>
</div

<!-- Modal -->
<div id="sel_grp_img" class="advanced-modal hide fade" role="dialog" aria-labelledby="grpImgModal" aria-hidden="true">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
    <h3  id="grpImgModal">选择图片</h3>
  </div>
  <div id="grp_img_body" class="modal-body">
  </div>
  <div class="modal-footer">
    <button id="grp_img_confirm" class="btn btn-primary">确认</button>
    <button class="btn" data-dismiss="modal" aria-hidden="true">关闭</button>
  </div>
</div>

app/views/image_groups/_groups_manage.html.erb
<div style="height: 400px;">
    <table class="table">
      <tr>
        <th>组id</th>
        <th>组名</th>
        <th>封面图片</th>
        <th>是否生效</th>
        <th>是否首页展示</th>
        <th>关键字</th>
        <th>图片组描述</th>
        <th>权重<strong class="text-error"><abbr title="权重值将决定图片组显示的先后顺序，权重值越小，显示越靠前"> *</abbr></strong></th>
        <th></th>
        <th></th>
      </tr>

    <% @image_groups.each do |image_group| %>
      <tr>
        <td><%= image_group.id %></td>
        <td><%= image_group.group_name %></td>
        <td><%= image_group.cover_image_id %></td>
        <td><%= (image_group.enabled==true) ? "是" : "否" %></td>
        <td><%= (image_group.promoted==true) ? "是" : "否" %></td>
        <td><%= image_group.key_word %></td>
        <td><%= image_group.desc %></td>
        <td><%= image_group.weight_factor %></td>
        <td><%= link_to '编辑', edit_image_group_path(image_group), remote:true, class:"btn btn-link" %></td>
        <td><%= link_to '删除', image_group, remote:true, method: :delete, data: { confirm: '确认删除?' }, class:"btn btn-link" %></td>
      </tr>
    <% end %>
    </table>
    <div style="position: absolute; left:0px; top: 250px;">
        <%= paginate @image_groups,:params => {:controller => 'image_groups', :action => 'index'}, :remote => true %>
        <%= link_to '新建图片组', new_image_group_path(category_id:category_id), remote:true, class:"btn btn-warning" %>
    </div>
</div>

app/views/image_groups/_image_shower.html.erb
<% for i in 1..@images.total_pages %>
	<ul class="thumbnails old-images">
		<% @images.page(i).each do |image| %>
			<li class="span4 abc">
				<i data-image-id="<%= image.id %>" <% if image.id == @group.cover_image_id || @contentSelection == 'true' %>class="icon-ok icon-white selected"<% end %>></i>
				<%= link_to image_tag("#{image.instance.url || image.location}"),"#" , class:"thumbnail thumbnail-selection" %>
				<!-- a 'mutiple' or 'non-mutiple' class will append to this link for mutiple or non-mutiple image selection, which will be added after the ajax invocation in the unobtrusive js image_select.js.erb -->
			</li>
		<% end %>
	</ul>
<% end  %>
<% if !@available_images.nil?  %>
<span>可选图片</span>
<hr>
	<% for i in 1..@available_images.total_pages %>
		<ul class="thumbnails new-images">
			<% @available_images.page(i).each do |image| %>
				<li class="span4 abc">
					<i data-image-id="<%= image.id %>" <% if image.id == @group.cover_image_id %>class="icon-ok icon-white selected"<% end %>></i>
					<%= link_to image_tag("#{image.instance.url || image.location}"),"#" , class:"thumbnail thumbnail-selection" %>
					<!-- a 'mutiple' or 'non-mutiple' class will append to this link for mutiple or non-mutiple image selection, which will be added after the ajax invocation in the unobtrusive js image_select.js.erb -->
				</li>
			<% end %>
		</ul>
	<% end  %>
<% end  %>

app/views/image_groups/create.js.erb
<% if @image_group.errors.any? %>
	$('#subpage-pane').html('<%= j render partial:'form' %>');
	<% @image_group.errors.each do |attribute, msg| %>
		$('#control-group-<%= attribute %>').addClass('error');
	<% end %>
<% else %>
	$("#ig-pills>.active>a").click();
<% end %>

app/views/image_groups/destroy.js.erb
$("#ig-pills>.active>a").click();

app/views/image_groups/edit.html.erb
<h1>Editing image_group</h1>

<%= render 'form' %>

<%= link_to 'Show', @image_group %> |
<%= link_to 'Back', image_groups_path %>

app/views/image_groups/edit.js.erb
$('#subpage-pane').html('<%= j render partial:'form' %>');

app/views/image_groups/image_select.js.erb
$("#modal_body").html('<%= j render 'image_shower' %>');

<% if @contentSelection == 'true' %>
	$("#modal_body").find("a").addClass("mutiple");

	//unbind click function on confirm button
	$('#btn_confirm').unbind('click');

	//bind confirmation funtion, this will display the selected image as cover image  on the image group page
	$("#btn_confirm").bind("click", function(){
		var removed_images = new Array(0);
		var added_images = new Array(0);
		
		//detect the removed image id
		$(".old-images").find("i").not(".selected").each(function(index){
			removed_images[index]=$(this).data("image-id");
		});
		//and store it within a hidden input named with images_removed
		$("#images_removed").val(removed_images.toString());

		//detect the new added image id
		$(".new-images").find("i.selected").each(function(index){
			added_images[index]=$(this).data("image-id");
		});

		//and store it within a hidden input named with images_added
		$("#images_added").val(added_images.toString());

		var content = "";
		$("i.selected+a>img").each(function(){
			content += "<img src='" + $(this).attr("src") + "' width='100'>";
		});

		$("#content_image").html(content);
		$("#select_img_modal").modal('hide');
	});
	//bind over

<% else %>
	$("#modal_body").find("a").addClass("non-mutiple");

	//unbind click function on confirm button
	$('#btn_confirm').unbind('click');

	//bind confirmation funtion, this will display the all the selected image on the main image group page
	$("#btn_confirm").bind("click", function(){
		var imgsrc = $("i.selected+a>img").attr("src");
        var image_id = $("i.selected").data("image-id");
        
        $("#cover_image").html("<img src='" + imgsrc + "' width='100'>");
        $("#cover_image").parent().find("input").val(image_id);
        $("#select_img_modal").modal('hide');
	});
	//bind over

<% end %>

$("#select_img_modal").modal('show');

app/views/image_groups/index.html.erb
<h1>Listing image_groups</h1>

<table>
  <tr>
    <th>Group id</th>
    <th>Group name</th>
    <th>Category</th>
    <th>Cover image</th>
    <th>Enabled</th>
    <th>Key word</th>
    <th>Desc</th>
    <th>Weight factor</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @image_groups.each do |image_group| %>
  <tr>
    <td><%= image_group.id %></td>
    <td><%= image_group.group_name %></td>
    <td><%= image_group.category %></td>
    <td><%= image_group.cover_image_id %></td>
    <td><%= image_group.enabled %></td>
    <td><%= image_group.key_word %></td>
    <td><%= image_group.desc %></td>
    <td><%= image_group.weight_factor %></td>
    <td><%= link_to 'Show', image_group %></td>
    <td><%= link_to 'Edit', edit_image_group_path(image_group) %></td>
    <td><%= link_to 'Destroy', image_group, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Image group', new_image_group_path %>

app/views/image_groups/index.js.erb
$('#subpage-pane').html('<%= j render :partial=>"groups_manage", locals:{category_id:@category_id} %>');
$('#ig-pills > li').removeClass("active");
$('#ig-pill-<%= @category_id %>' ).addClass("active");

app/views/image_groups/new.html.erb
<h1>New image_group</h1>

<%= render 'form' %>

<%= link_to 'Back', image_groups_path %>

app/views/image_groups/new.js.erb
$('#subpage-pane').html('<%= j render :partial=>"form", locals:{ category_id:@category_id } %>');

app/views/image_groups/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Group name:</b>
  <%= @image_group.group_name %>
</p>

<p>
  <b>Category:</b>
  <%= @image_group.category %>
</p>

<p>
  <b>Cover image:</b>
  <%= @image_group.cover_image_id %>
</p>

<p>
  <b>Enabled:</b>
  <%= @image_group.enabled %>
</p>

<p>
  <b>Key word:</b>
  <%= @image_group.key_word %>
</p>

<p>
  <b>Desc:</b>
  <%= @image_group.desc %>
</p>

<p>
  <b>Weight factor:</b>
  <%= @image_group.weight_factor %>
</p>


<%= link_to 'Edit', edit_image_group_path(@image_group) %> |
<%= link_to 'Back', image_groups_path %>

app/views/image_groups/update.js.erb
<% if @image_group.errors.any? %>
	$('#subpage-pane').html('<%= j render partial:'form' %>');
	<% @image_group.errors.each do |attribute, msg| %>
		$('#control-group-<%= attribute %>').addClass('error');
	<% end %>
<% else %>
	$("#ig-pills>.active>a").click();
<% end %>