config/routes.rb
Nyweb::Application.routes.draw do
  get "password_resets/new"

  get "password_resets/edit"

  get "password_resets/update"

  resources :image_groups

  resources :images
  resources :comments, :only => [:create, :destroy, :show]

  resources :users#, :only => [:show, :update,:edit]
  resources :sessions, :only => [:new, :create, :destroy]
  resources :messages, :only => [:index, :new, :create, :show, :destroy]
  resources :password_resets

  get "pub/index"

  root to: 'pub#index'  
  match "/about" => "pub#about"
  match "/contact" => "pub#contact"
  match "/recruit" => "pub#recruit"
  match "/ba" => "pub#ba"
  match "/signout" => "sessions#destroy"
  match "/education" => "pub#edu"
  match "/cate" => "pub#cate"
  match "/fab" => "pub#fab"
  match "/tour" => "pub#tour"
  match "/beauty" => "pub#beauty"
  match "/entertainment" => "pub#entertainment"
  match "/show" => "pub#show"
  match "/decoration" => "pub#decoration"
  match "/promotion" => "pub#promotion"

  match "/slide_modal/:id" => "pub#showSlideModal"
  match "/slide_modal" => "pub#showSlideModalFake"

  match "/update_password" => "users#updatePWD"
  match "/update_email" => "users#updateEmail"
  match "/update_address" => "users#updateAddress"
  match "/update_phone" => "users#updatePhone"

  match "/admin" => "admin#index"
  match "/image_select" => "image_groups#image_select"
  match "/gravatar" => "pub#gravatar"

  match "*a" => "pub#render_404"

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :address, :email, :password,:password_confirmation, :phone, :username, :remember_me, :avatar
  attr_accessor :remember_me
  has_many :comments
  has_many :leave_messages
  mount_uploader :avatar, AvatarUploader

  #has_secure_password

  before_save { |user| user.email = email.downcase }
  before_save :create_remember_token, :unless => Proc.new { |u| u.password.blank? }

  validates :username, presence: {message: "用户名不能为空"}, 
  length: { maximum: 50, message: "用户名不能超过50个字符" },
  uniqueness: { case_sensitive: false, message:"用户名已经被占用" }

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: { message:"email地址不能为空" },
  format: { with: VALID_EMAIL_REGEX,message:"email地址不正确，请确认" },
  uniqueness: { case_sensitive: false, message:"email地址已经被使用" }

  validates :phone, 	presence: {message: "手机号码不能为空"}, 
  length: {is:11,message:"手机号码长度不正确"}, 
  numericality: { only_integer: true, message:"手机号码只能包含数字" }, 
  uniqueness: { message:"该手机号码已经被注册使用" }
  validates :password, 	presence: {message: "密码不能为空"}, 
  length: { minimum: 6,message:"密码至少为6位数字及字母" }, 
  confirmation: {message:"两次输入的密码不匹配"} , :if => :password_required?
  validates :password_confirmation, presence: {message: "确认密码不能为空"}, :if => :password_required?

  has_secure_password

  def send_password_reset
    generate_token(:password_reset_token)
    self.password_reset_sent_at = Time.zone.now
    save!
    UserMailer.password_reset(self).deliver
  end

  def generate_token(column)
    begin
      self[column] = SecureRandom.urlsafe_base64
    end while User.exists?(column => self[column])
  end

  private
  def create_remember_token
    self.remember_token = SecureRandom.urlsafe_base64
  end

  private
  def password_required?
  	password_digest.blank? || !password.blank?
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
require 'digest'
include SessionsHelper

# GET /users
# GET /users.json
def index
  @users                      = User.all

  respond_to do |format|
  format.html # index.html.erb
  format.json { render json: @users }
end
end

# GET /users/1
# GET /users/1.json
def show
  @user                       = User.find(params[:id])

  respond_to do |format|
    format.html # show.html.erb
    format.json { render json: @user }
  end
end

# GET /users/new
# GET /users/new.json
def new
  @user                       = User.new

  respond_to do |format|
format.html # new.html.erb
format.json { render json: @user }
end
end

# GET /users/1/edit
def edit
  @user                       = User.find(params[:id])
end

# POST /users
# POST /users.json
def create
  @user = User.new(params[:user])

  authCode = Digest::MD5.hexdigest params[:auth][:authCode]

  if authCode != params[:auth][:hiddenAuthCode]
    @user.errors.add(:authcode,"短信验证码输入不正确")
    return
  end
  
  respond_to do |format|
    if @user.save
      sign_in @user
      puts "success!"
      puts "2222:" + signed_in?.to_s
      format.html { redirect_to root_path }
      format.json { render json: @user, status: :created, location: @user }
      format.js {}
    else
      puts "save user failed"
      puts @user.errors.count
      puts @user.errors.full_messages
      #puts @user.errors.get(:username)

      format.html { render action: "new" }
      format.json { render json: @user.errors, status: :unprocessable_entity }
      format.js {}
      #format.js { render :partial => 'users/login', :locals => { :user => @user }}
    end
  end
end

# PUT /users/1
# PUT /users/1.json
def update
  @user                       = User.find(params[:id])
  p @user.avatar.url
  respond_to do |format|
    if @user.update_attributes(params[:user])
      format.html { redirect_to @user, notice: '用户信息更新成功！' }
      format.json { head :no_content }
    else
      format.html { render action: "edit" }
      format.json { render json: @user.errors, status: :unprocessable_entity }
    end
  end
end

def updatePWD
	if signed_in?
		@user = current_user
		if params[:user][:password].blank? || params[:user][:password_confirmation].blank?
			@user.errors.add(:password, "密码及确认密码不能为空.")
		elsif   @user.authenticate(params[:user][:old_password])
			@user.password = params[:user][:password]
			@user.password_confirmation = params[:user][:password_confirmation]
			@user.save
		else
			@user.errors.add(:password_incorrect, "旧密码输入不正确，请确认.")
			puts "更改密码失败"
		end
	elsif
		@user = User.new
		@user.errors.add(:not_signed_in, "您尚未登录，请先登录再尝试修改密码.")
	end

	respond_to do |format|
      		format.html { redirect_to @user, notice: 'User was successfully updated.' }
      		format.json { head :no_content }
      		format.js   {}
   	end
	
end

def updateEmail
        if signed_in?
                @user = current_user
                @user.email = params[:user][:email]
		puts @user.email
		puts @user.valid?
		if @user.valid?
			@user.update_attribute(:email,params[:user][:email])
		end
        elsif
                @user = User.new
                @user.errors.add(:not_signed_in, "您尚未登录，请先登录再尝试修改.")
        end

        respond_to do |format|
                format.html { redirect_to @user, notice: 'User was successfully updated.' }
                format.json { head :no_content }
                format.js   {}
        end

end

def updateAddress
        if signed_in?
                @user = current_user
                @user.address = params[:user][:address]
                puts @user.address
                puts @user.valid?
                if @user.valid?
                        @user.update_attribute(:address,params[:user][:address])
                end
        elsif
                @user = User.new
                @user.errors.add(:not_signed_in, "您尚未登录，请先登录再尝试修改.")
        end

        respond_to do |format|
                format.html { redirect_to @user, notice: 'User was successfully updated.' }
                format.json { head :no_content }
                format.js   {}
        end

end

def updatePhone
        if signed_in?
                @user = current_user
                @user.phone = params[:user][:phone]
		
		if params[:auth][:authCode].blank?
                        @user.errors.add(:authcode,"请输入验证码")
                        return
                end
        	
		if params[:auth][:authCode] != params[:auth][:hiddenAuthCode] 
			@user.errors.add(:authcode,"短信验证码输入不正确")
                	return
        	end
                
		if @user.valid?
                        @user.update_attribute(:phone,params[:user][:phone])
                end
        elsif
                @user = User.new
                @user.errors.add(:not_signed_in, "您尚未登录，请先登录再尝试修改.")
        end

        respond_to do |format|
                format.html { redirect_to @user, notice: 'User was successfully updated.' }
                format.json { head :no_content }
                format.js   {}
        end

end

# DELETE /users/1
# DELETE /users/1.json
def destroy
  @user                       = User.find(params[:id])
  @user.destroy

  respond_to do |format|
    format.html { redirect_to users_url }
    format.json { head :no_content }
  end
end
end

app/helpers/users_helper.rb
module UsersHelper
	def gravatar_for(user, version)
		# Returns the Gravatar (http://gravatar.com/) for the given user.
		gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
		gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
		
		if (version == :minor)
		  image_tag(gravatar_url, alt: user.username,  height: '48', width: '48', class:'gravatar')
		elsif (version == :mini)
		  image_tag(gravatar_url, alt: user.username,  height: '30', width: '30', class:'gravatar')
		else
		  image_tag(gravatar_url, alt: user.username, class: 'gravatar')
		end	
	end
	
	def default_minor_avatar
		image_tag("/assets/images/avatar/minor_avatar.jpg",height: '48', width: '48', class:'gravatar') 
	end

	def default_mini_avatar
		image_tag("/assets/images/avatar/mini_avatar.jpg",height: '30', width: '30', class:'gravatar') 
	end

end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :username %><br />
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.text_field :password %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :phone %><br />
    <%= f.text_field :phone %>
  </div>
  <div class="field">
    <%= f.label :address %><br />
    <%= f.text_field :address %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/_login.html.erb
   <% if !signed_in? %>
   <a class="btn btn-link" data-toggle="modal" href="#loginModal">登录</a>&nbsp;
   <a class="btn btn-link" data-toggle="modal" href="#registerModal">注册</a>
   <%= link_to "留言", new_message_path, html_options = {id:"message-anchor", class:"btn btn-link btn-mini", :'data-toggle'=>"tooltip", :'data-placement'=>"bottom",:'data-original-title'=>"给我们留言" } %>

   <div id="loginModal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h3 id="myModalLabel">用户登录</h3>
    </div>
    <div class="modal-body">
        <%= form_for(user, url: { controller: "sessions", action: "create" } , remote:true, html: {id: "user_login",class: "form-horizontal"}) do |u| %>
        <div id="login_error_explanation" class="alert alert-error hide text-center">
        </div>
        <fieldset>
            <div class="control-group">
                <div class="controls input-prepend">
                    <span class="add-on"><i class="icon-user"></i></span>
                    <%= u.text_field :username, placeholder:"用户名", id:"login_user_name" %>
                </div>
            </div>
            <br>
            <div class="control-group">
                <div class="controls  input-prepend">
                    <span class="add-on"><i class="icon-lock"></i></span>
                    <%= u.password_field :password, placeholder:"密码", id:"login_user_password" %>
                </div>
            </div>
            <div class="control-group">
                <div class="controls input-prepend">
                    <%= u.label(:remember_me, class:"checkbox") do %>
                    <%= u.check_box :remember_me,  {} , "true" , "false" %>
                    记住我
                    <% end %>
                    <%= link_to "忘记密码？", new_password_reset_path, class:"btn btn-link" %>             
                </div>
            </div>
        </fieldset>
        <% end %>
    </div>
    <div class="modal-footer centered">
        <button type="submit" class="btn btn-primary" form="user_login">登录</button>
    </div>
</div>
<!--register modal-->
<div id="registerModal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="registerLabel" aria-hidden="true">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h3 id="registerLabel">新用户注册</h3>
    </div>
    <div class="modal-body">
        <%= form_for(user, remote:true, html: {id: "user_register",class: "form-horizontal"}) do |u| %>
        <div id="error_explanation" class="alert alert-error hide">

        </div>
        <fieldset>
            <div id="control-group-username" class="control-group">
                <label class="control-label" for="username">用户名<strong class="text-error"><abbr title="必填项"> *</abbr></strong></label>
                <div class="controls">
                    <%=u.text_field :username, :placeholder=>"用户名"%>
                </div>
            </div>
            <div id="control-group-password" class="control-group">
                <label class="control-label" for="password">密码<strong class="text-error"><abbr title="必填项"> *</abbr></strong></label>
                <div class="controls">
                    <%=u.password_field :password, :placeholder=>"密码"%>
                </div>
            </div>
            <div id="control-group-password_confirmation" class="control-group">
                <label class="control-label" for="password_confirmation">再次确认密码<strong class="text-error"><abbr title="必填项"> *</abbr></strong></label>
                <div class="controls">
                    <%=u.password_field :password_confirmation, :placeholder=>"再次确认密码"%>
                </div>
            </div>
            <div id="control-group-email" class="control-group">
                <label class="control-label" for="mailbox">注册邮箱<strong class="text-error"><abbr title="必填项"> *</abbr></strong></label>
                <div class="controls">
                    <%=u.text_field :email, :placeholder=>"注册邮箱"%>
                </div>
            </div>
            <div id="control-group-phone" class="control-group">
                <label class="control-label" for="cellphone">手机号码<strong class="text-error"><abbr title="必填项"> *</abbr></strong></label>
                <div class="controls">
                    <%=u.text_field :phone, :placeholder=>"手机号码"%>
                </div>
            </div>
            <div class="control-group">
                <div class="controls">
                    <button type="button" id="sendSMS" class="btn">发送验证码</button>
                    <!--<%= link_to "发送验证码", id:"sendSMS", class:"btn" %>-->
                </div>
            </div>
            <div id="control-group-authcode" class="control-group">
                <label class="control-label" for="cellphone">验证码<strong class="text-error"><abbr title="必填项"> *</abbr></strong></label>
                <div class="controls">
                    <%= text_field "auth",  "authCode", :placeholder=>"验证码"%>
                    <%= hidden_field "auth", "hiddenAuthCode" %>
                </div>
            </div>
        </fieldset>
        <% end %>

    </div>
    <div class="modal-footer centered">
        <button type="submit" class="btn btn-primary" form="user_register">注册</button>
    </div>
</div>
<% else %>
<div>
    <!--<%= button_to "退出", signout_path , form_class:"no-margin" ,class:"btn btn-default"%>-->
    <!--<%= link_to current_user.username, class:"btn btn-link" %>-->
    <div class="btn-group">
        <%= link_to "退出", signout_path, class:"btn btn-info" %>
        <button class="btn btn-success dropdown-toggle" data-toggle="dropdown">
            <span class="caret"></span>
        </button>
        <ul class="dropdown-menu">
            <li>
                <%= link_to(current_user) do %>
                <span class='icon-edit'></span> 个人资料
                <% end %>
            </li>
            <li><a href="#"><span class="icon-wrench"></span> 修改密码</a></li>
            <% if current_user.admin==true %>
            <li><a href="/admin"><span class="icon-briefcase"></span> 后台管理</a></li>
            <% end  %>
        </ul>
    </div>
    <%= link_to "留言", new_message_path, html_options = {id:"message-anchor", class:"btn btn-link btn-mini", :'data-toggle'=>"tooltip", :'data-placement'=>"bottom",:'data-original-title'=>"给我们留言" } %>
</div>
<% end %>

app/views/users/create.js.erb
<% if @user.errors.any? %>
	var error_block = "";
	$(".control-group").removeClass("error");
	<% @user.errors.each do |attribute, msg| %>
		error_block +=  '<li><%= msg %></li>';
		$('#control-group-<%= attribute %>').addClass('error');
		<% if attribute == :phone %>
			$("#user_phone").removeAttr("readonly");
		        $("#user_phone").unbind("change");
			$("#auth_hiddenAuthCode").val('');
			$("#auth_authCode").val('');
		<% end %>
	<% end %>
	$("#error_explanation").html("<ul>" + error_block + "</ul>" );
	$("#error_explanation").show();
<% else %>
	$('#registerModal').modal('toggle');
	$('#regSucModal').modal('toggle');
	$("#user_zone").html("<%= j render partial:'users/login', locals:{ user: @user } %>");
<% end %>

app/views/users/index.html.erb
<% if signed_in? && (current_user.admin == true) %>
    <div class="container">
    <h1>所有注册用户</h1>

    <table class="table">
      <tr>
        <th>用户名</th>
        <th>Email</th>
        <th>Phone</th>
        <th>Address</th>
        <th></th>
        <th></th>
        <th></th>
      </tr>

    <% @users.each do |user| %>
      <tr>
        <td><%= user.username %></td>
        <td><%= user.email %></td>
        <td><%= user.phone %></td>
        <td><%= user.address %></td>
        <td><%= link_to '查看', user %></td>
        <td><%= link_to '编辑', edit_user_path(user) %></td>
        <td><%= link_to '删除', user, method: :delete, data: { confirm: '确认删除?' } %></td>
      </tr>
    <% end %>
    </table>

    <br />
    </div>
<% else %>
    <div class="container" style="height: 600px;">
        <hr>
        <div class="alert alert-error">无访问权限</div>
    </div>
<% end  %>

app/views/users/show.html.erb
<% if signed_in? && (current_user.id == @user.id) %>
<div class="container">
  <hr>
  <div class="tabbable tabs-left" style="height: 500px;">
    <div class="float-left">
      <ul class="thumbnails">
        <li>
          <%= link_to(@user, class:"thumbnail") do %>
            <% if @user.avatar.thumb.url.nil?  %>
              <%= gravatar_for(@user, :thumb) %>
            <% else %>
              <%= image_tag @user.avatar.thumb.url %>
            <% end  %>
          <% end %>
        </li>
      </ul>     
      <div>
        <em>&nbsp;<%= link_to @user.username, user_path(@user) %></em> 
      </div>
    </div>

    <ul class="nav nav-tabs nav-stacked">
      <li class="active"><a href="#avatar" data-toggle="tab">头像设置</a></li>
      <li><a href="#pane1" data-toggle="tab">基本信息</a></li>
      <li><a href="#pane2" data-toggle="tab">更改密码</a></li>
      <li><a href="#pane3" data-toggle="tab">更改email地址</a></li>
      <li><a href="#pane4" data-toggle="tab">更改手机号码</a></li>
      <li><a href="#pane5" data-toggle="tab">更改地址信息</a></li>
    </ul>
    <div class="tab-content">
      <div id="avatar" class="tab-pane active">
        <p>本站支持自定义头像，以及Gravatar头像，但我们鼓励你使用
          <abbr title="什么是Gravatar?"><%= link_to "Gravatar", gravatar_path %></abbr>头像
        </p>
        <p>如果你在两种头像均有设定的情况下，我们将优先显示你的自定义头像</p>
        <h4>自定义头像</h4>
        <% if flash[:notice] %>
          <div class="notice alert alert-success"><%= flash[:notice] %></div>
        <% end %>
        
        <%= form_for(@user, html: {class: "form-horizontal"}) do |u| %>
          <div class="control-group">
            <div class="controls">
              <ul class="thumbnails">
                <li>
                  <a href="#" class="thumbnail">
                    <% if @user.avatar.thumb.url.nil?  %>
                      <%= image_tag "/assets/images/avatar/avatar.gif" %>
                    <% else %>
                      <%= image_tag @user.avatar.thumb.url %>
                    <% end  %>
                  </a>
                </li>
              </ul>
            </div>
          </div>  
          <div class="control-group">
            <label class="control-label" for="old_password"><strong class="text-success">头像设置</strong></label>
            <div class="controls">
              <span class="btn btn-success fileinput-button">  
                <i class="icon-plus icon-white"></i>  
                <span>选择图片...</span>  
                <%= u.file_field :avatar %>  
              </span>  
            </div>
          </div>  
          <div class="control-group">
            <div class="controls">
              <%= u.submit "提交", class:"btn btn-warning" %>
            </div>
          </div>
          <br>
          <h4>Gravatar头像</h4>
          <div>
            <div class="control-group">
              <div class="controls">
                <%= link_to "更改Gravatar头像", "http://gravatar.com/emails", class:"btn btn-success" %> 
              </div>
            </div>
          </div>
        <% end %>
        <%#= link_to 'Edit', edit_user_path(@user) %>
      </div>
      <div id="pane1" class="tab-pane">
        <p id="notice"><%= notice %></p>

        <table class="table table-hover">
          <tbody>
            <tr class="success">
              <td><b class="text-success">用户名:</b></td><td><%= @user.username %></td>
            </tr>
            <tr class="error">
              <td><b  class="text-success">Email地址:</b></td><td><%= @user.email %></td>
            </tr>
            <tr class="warning">
              <td><b  class="text-success">手机号码:</b></td><td><%= @user.phone %></td>
            </tr>
            <tr class="info">
              <td><strong  class="text-success">地址信息:</strong></td><td><%= @user.address %></td>
            </tr>
          </tbody>
        </table>
        <%#= link_to 'Edit', edit_user_path(@user) %>
      </div>
      <div id="pane2" class="tab-pane">
        <div id="update_password_response" class="alert hide fade in">
          <button type="button" class="close close-btn">&times;</button>
          <p id="update_password_response_msg"></p>
        </div>
        <div id="redirect-warning" class="hide">
          <span class="label label-warning">注意</span>
          <a id="redirect_anchor" href="/">您需要重新使用新密码登录，页面将在<span id="countDown">5</span>秒之后跳转到首页，您可以点击这里直接跳转</a>
          <div class="progress progress-warning">
            <div id="redirect-bar" class="bar" style="width: 0%;"></div>
          </div>
        </div>
        <%= form_for(@user, url: {controller: "users", action: "updatePWD"} , remote:true,  html: {id: "user_login",class: "form-horizontal"}) do |u| %>
        <div class="control-group">
          <label class="control-label" for="old_password"><strong class="text-success">旧密码</strong></label>
          <div class="controls">
            <%= u.password_field :old_password, id:"old_password", :placeholder=>"旧密码"%>
          </div>
        </div>
        <div class="control-group">
          <label class="control-label" for="password"><strong class="text-success">新密码</strong></label>
          <div class="controls">
            <%= u.password_field :password, :placeholder=>"新密码", id:"password" %>
          </div>
        </div>
        <div class="control-group">
          <label class="control-label" for="password_confirmation"><strong class="text-success">再次输入新密码</strong></label>
          <div class="controls">
            <%= u.password_field :password_confirmation, :placeholder=>"新密码", id:"password_confirmation" %>
          </div>
        </div>
        <div class="control-group">
          <div class="controls">
            <%= u.submit "提交", class:"btn btn-warning" %>
          </div>
        </div>
        <% end %>
      </div>
      <div id="pane3" class="tab-pane">
        <div id="update_email_response" class="alert hide fade in">
          <button type="button" class="close close-btn">&times;</button>
          <p id="update_email_response_msg"></p>
        </div>
        <%= form_for(@user, url: {controller: "users", action: "updateEmail"} , remote:true,  html: {id: "user_login",class: "form-horizontal"}) do |u| %>
        <div class="control-group">
          <label class="control-label" for="email"><strong class="text-success">Email地址</strong></label>
          <div class="controls">
            <%= u.text_field :email, id:"email", value:@user.email %>
          </div>
        </div>
        <div class="control-group">
          <div class="controls">
            <%= u.submit "提交", class:"btn btn-warning" %>
          </div>
        </div>
        <% end %>
      </div>
      <div id="pane4" class="tab-pane">
        <div id="update_phone_response" class="alert hide fade in">
          <button type="button" class="close close-btn">&times;</button>
          <p id="update_phone_response_msg"></p>
        </div>
        <%= form_for(@user, url: {controller: "users", action: "updatePhone"} , remote:true,  html: {id: "user_login",class: "form-horizontal"}) do |u| %>
        <div class="control-group">
          <label class="control-label" for="email"><strong class="text-success">当前手机号码</strong></label>
          <div class="controls">
            <%= u.text_field :old_phone, value:@user.phone, disabled:true %>
          </div>
        </div>
        <div class="control-group">
          <label class="control-label" for="new_phone"><strong class="text-success">新手机号码</strong></label>
          <div class="controls">
            <%= text_field "user", "phone", placeholder:"新手机号码", value:''%>
          </div>
        </div>
        <div class="control-group">
          <div class="controls">
            <%= u.button "发送验证码", remote:true, id:"sendSMS", class:"btn btn-warning" %>
          </div>
        </div>
        <div class="control-group">
          <label class="control-label" for="auth_code"><strong class="text-success">验证码</strong></label>
          <div class="controls">
            <%= text_field "auth","authCode", placeholder:"验证码" %>
            <%= hidden_field "auth", "hiddenAuthCode" %>
          </div>
        </div>
        <div class="control-group">
          <div class="controls">
            <%= u.submit "提交", class:"btn btn-warning" %>
          </div>
        </div>
        <% end %>
      </div>
      <div id="pane5" class="tab-pane">
        <div id="update_address_response" class="alert hide fade in">
          <button type="button" class="close close-btn">&times;</button>
          <p id="update_address_response_msg"></p>
        </div>
        <%= form_for(@user, url: {controller: "users", action: "updateAddress"} , remote:true,  html: {id: "user_login",class: "form-horizontal"}) do |u| %>
        <div class="control-group">
          <label class="control-label" for="address"><strong class="text-success">地址信息</strong></label>
          <div class="controls">
            <%= u.text_field :address, id:"address", value:@user.address, size:150 %>
          </div>
        </div>
        <div class="control-group">
          <div class="controls">
            <%= u.submit "提交", class:"btn btn-warning" %>
          </div>
        </div>
        <% end %>
      </div>
    </div>
  </div>
</div>
<% else %>
    <div class="container" style="height: 600px;">
        <hr>
        <div class="alert alert-error">你无权问该注册用户个人信息</div>
    </div>
<% end  %>

app/views/users/updateAddress.js.erb
<% if @user.errors.any? %>
        var error_block = "";
        <% @user.errors.each do |attribute, msg| %>
                error_block +=  '<li><%= msg %></li>';
        <% end %>
	
        $("#update_address_response_msg").html("<ul>" + error_block + "</ul>" );
        $("#update_address_response").removeClass("alert-success");
        $("#update_address_response").addClass("alert-error");
        $("#update_address_response").show();
<% else %>
	$("#update_address_response_msg").html("地址信息修改成功.");
        $("#update_address_response").removeClass("alert-error");
        $("#update_address_response").addClass("alert-success");
        $("#update_address_response").show();
<% end %>

app/views/users/updateEmail.js.erb
<% if @user.errors.any? %>
        var error_block = "";
        <% @user.errors.each do |attribute, msg| %>
                error_block +=  '<li><%= msg %></li>';
        <% end %>
	
        $("#update_email_response_msg").html("<ul>" + error_block + "</ul>" );
        $("#update_email_response").removeClass("alert-success");
        $("#update_email_response").addClass("alert-error");
        $("#update_email_response").show();
<% else %>
	$("#update_email_response_msg").html("email地址修改成功.");
        $("#update_email_response").removeClass("alert-error");
        $("#update_email_response").addClass("alert-success");
        $("#update_email_response").show();
<% end %>