config/routes.rb
Nyweb::Application.routes.draw do
  get "password_resets/new"

  get "password_resets/edit"

  get "password_resets/update"

  resources :image_groups

  resources :images
  resources :comments, :only => [:create, :destroy, :show]

  resources :users#, :only => [:show, :update,:edit]
  resources :sessions, :only => [:new, :create, :destroy]
  resources :messages, :only => [:index, :new, :create, :show, :destroy]
  resources :password_resets

  get "pub/index"

  root to: 'pub#index'  
  match "/about" => "pub#about"
  match "/contact" => "pub#contact"
  match "/recruit" => "pub#recruit"
  match "/ba" => "pub#ba"
  match "/signout" => "sessions#destroy"
  match "/education" => "pub#edu"
  match "/cate" => "pub#cate"
  match "/fab" => "pub#fab"
  match "/tour" => "pub#tour"
  match "/beauty" => "pub#beauty"
  match "/entertainment" => "pub#entertainment"
  match "/show" => "pub#show"
  match "/decoration" => "pub#decoration"
  match "/promotion" => "pub#promotion"

  match "/slide_modal/:id" => "pub#showSlideModal"
  match "/slide_modal" => "pub#showSlideModalFake"

  match "/update_password" => "users#updatePWD"
  match "/update_email" => "users#updateEmail"
  match "/update_address" => "users#updateAddress"
  match "/update_phone" => "users#updatePhone"

  match "/admin" => "admin#index"
  match "/image_select" => "image_groups#image_select"
  match "/gravatar" => "pub#gravatar"

  match "*a" => "pub#render_404"

end

app/controllers/pub_controller.rb
class PubController < ApplicationController
  include SessionsHelper
  #puts signed_in?.to_s + "<<<<<<<<<<<<<<<<<<>>>>>>>>>>>>>>>>>>>"
  @user
  @auth_code

  def get_current_user
   @user = (signed_in?) ? current_user : User.new
 end

 def getImageGroup(category_id, promoted)
   if category_id == nil
    category_id = 1
  end

  add_where = " "

  if !promoted.nil?
    add_where = " and promoted = true "
  end

  ImageGroup.order("weight_factor asc").where(" enabled = true and category_id = '#{category_id}' #{add_where} ").page(1)
end

def index
  get_current_user 
  @gc = Hash.new
  #get all the categories
  @all_categorys = Category.order("id")

  #get image groups base on the categories
  @all_categorys.each do |c|
    @gc[c.name] = getImageGroup(c.id, true)
  end

  p @gc.length
end

def about
  get_current_user 
end

def contact
  get_current_user 
end

def recruit
  get_current_user 
end

def ba
  get_current_user 
end

def edu
	get_current_user
	@groups = getImageGroup(1, nil)
	@comments = Comment.page(params[:page])
	
	@groups.each do |g|
		puts g.group_name
	end
end

def cate
  get_current_user 
  @groups = getImageGroup(2, nil)
end

def fab
  get_current_user 
  @groups = getImageGroup(6, nil)
end

def tour
  get_current_user 
  @groups = getImageGroup(3,nil)
end

def beauty
  get_current_user 
  @groups = getImageGroup(4, nil)
end

def entertainment
  get_current_user 
  @groups = getImageGroup(5, nil)
end 

def sos
  get_current_user 
  @groups = getImageGroup('sos')
end

def show
  get_current_user
  @groups = getImageGroup(7, nil)
end

def decoration
  get_current_user 
  @groups = getImageGroup(8, nil)
end

def promotion
  get_current_user
  @groups = getImageGroup(9, nil)
end

def sendSMS
 @auth_code=123223
 puts @auth_code
 respond_to do |format|
  format.html { render nothing: true }
  format.js {}
end
end

def showSlideModal
	#simulate a fake group
	@group = ImageGroup.find(params[:id])
	puts @group.id
	
	@images = @group.images.order("weight_factor asc")
	
	first_image_id = @images.first.id	
	@comments = @images.first.comments.order("id asc").page(1)
	params[:id]= first_image_id
	@images.each {|i| puts i.location}
	#will render showSlideModal.js.erb
end

def showSlideModalFake
	#simulate a fake group
	@group = ImageGroup.find(5)
	puts @group.id
	
	@images = @group.images.order("weight_factor asc")
	
	first_image_id = @images.first.id	
	@comments = @images.first.comments.order("id asc").page(1)

	@images.each {|i| puts i.location}
end

def admin
	@image_groups = getImageGroup(1, nil)
	@categorys = Category.all
	puts @image_groups.size
end

def gravatar
end

def render_404
	puts "404 error, received url not correct"
	respond_to do |format|
    format.html { render "public/404.html", layout: false }
    format.js {}
  end
end
end

app/helpers/pub_helper.rb
module PubHelper
end

app/views/pub/_image_groups.html.erb
<% for i in 1..@groups.total_pages %>
	<ul class="thumbnails">
		<% @groups.page(i).each do|group| %>
			<li class="span4">
				<%= link_to image_tag("#{group.cover.instance.url || group.cover.location}", class:"img-cover"), "slide_modal/#{group.id}", class:"thumbnail", remote:true %>
			</li>
		<% end %>
	</ul>
<% end %>

app/views/pub/ba.html.erb
<div style="height: 600px">
</div>

app/views/pub/beauty.html.erb
<div class="slide-bar">
  <div class="container">
    <div id="edu_slide" class="banner">
      <ul>
        <li><img src="assets/images/beauty/slide/01.jpg" alt="prod_show" /></li>
        <li><img src="assets/images/beauty/slide/02.jpg" alt="prod_show" /></li>
      </ul>
    </div>
  </div>
</div>

<div class="navbar navbar-static-top navbar-inverse" data-spy="affix" data-offset-top="400">
  <div class="navbar-inner">
    <div class="container">
      <a class="brand" href="#">优 · 美</a>
      <a class="brand"><small><em>也您是优秀的美容高手或者是美丽的机构正在为这个世界创造美，我们时间不足，没有找到您，在此深深道歉。</em></small></a>
      <!-- 
      <ul class="nav">
        <li><a href="#makeup">彩色香氛</a></li>
        <li><a href="#beautyparlor">美丽院线</a></li>        
        <li><a href="#hairdressing">发色发香</a></li>
        <li><a href="#spa">美体SPA</a></li>
        <li><a href="#sharp">形体瘦身</a></li>
        <li><a href="#fitness">健身club</a></li>
        <li><a href="#cosmetic">化妆品</a></li>
      </ul>
      <form class="navbar-search pull-left">
        <input type="text" class="search-query" placeholder="Search">
      </form>
      -->
    </div>
  </div>
</div>
<!--news div-->
<a id="makeup"></a>
<br>
<div class="container modules">
  <div class="row-fluid">
    <%= render :partial=>'image_groups' %>
  </div>
</div>

<script type="text/javascript">
$('#edu_slide').unslider({
  fluid: true,
  keys: true,               //  Enable keyboard (left, right) arrow shortcuts
  dots: true
});
</script>

app/views/pub/cate.html.erb
<div class="slide-bar">
  <div class="container">
    <div id="edu_slide" class="banner">
      <ul>
        <li><img src="assets/images/cate/slide/01.jpg" alt="prod_show" /></li>
      </ul>
    </div>
  </div>
</div>

<div class="navbar navbar-static-top navbar-inverse" data-spy="affix" data-offset-top="400">
  <div class="navbar-inner">
    <div class="container">
      <a class="brand" href="#">优 · 肴</a>
      <a class="brand"><small><em>也许您是优秀的炒菜高手或者是优雅的餐饮正在提供美味的佳肴，我们时间不足，没有找到您，在此深深道歉。</em></small></a>
      <!-- 
      <ul class="nav">
        <li class="dropdown">
          <a id="drop1" href="#" role="button" class="dropdown-toggle" data-toggle="dropdown">中餐 <b class="caret"></b></a>
          <ul class="dropdown-menu" role="menu" aria-labelledby="drop1">
            <li role="presentation"><a role="menuitem" tabindex="-1" href="#p-yuwen">川菜</a></li>
            <li role="presentation"><a role="menuitem" tabindex="-1" href="#p-shuxue">粤菜</a></li>
            <li role="presentation"><a role="menuitem" tabindex="-1" href="#p-english">烧烤</a></li>
            <li role="presentation"><a role="menuitem" tabindex="-1" href="#p-english">火锅</a></li>
          </ul>
        </li>
        <li class="dropdown">
          <a id="drop2" href="#" role="button" class="dropdown-toggle" data-toggle="dropdown">西餐 <b class="caret"></b></a>
          <ul class="dropdown-menu" role="menu" aria-labelledby="drop2">
            <li role="presentation"><a role="menuitem" tabindex="-1" href="#j-yuwen">西冷牛排</a></li>
            <li role="presentation"><a role="menuitem" tabindex="-1" href="#j-shuxue">豪客来</a></li>
            <li role="presentation" class="divider"></li>
            <li role="presentation"><a role="menuitem" tabindex="-1" href="#j-english">肯德基</a></li>
            <li role="presentation"><a role="menuitem" tabindex="-1" href="#j-physics">麦当劳</a></li>
            <li role="presentation"><a role="menuitem" tabindex="-1" href="#j-chemistry">披萨</a></li>
          </ul>
        </li>
        <li class="dropdown">
          <a id="drop3" href="#" role="button" class="dropdown-toggle" data-toggle="dropdown">自助餐 <b class="caret"></b></a>
          <ul class="dropdown-menu" role="menu" aria-labelledby="drop3">
            <li role="presentation" class="nav-header">区&nbsp;&nbsp;&nbsp;域</li>
            <li role="presentation"><a role="menuitem" tabindex="-1" href="#s-yuwen"></a></li>
            <li role="presentation"><a role="menuitem" tabindex="-1" href="#s-shuxue">兴庆区</a></li>
            <li role="presentation"><a role="menuitem" tabindex="-1" href="#s-english">金凤区</a></li>
            <li role="presentation"><a role="menuitem" tabindex="-1" href="#s-physics">西夏区</a></li>
          </ul>
        </li>
        <li class="dropdown">
          <a id="drop4" href="#" role="button" class="dropdown-toggle" data-toggle="dropdown">清真 <b class="caret"></b></a>
          <ul class="dropdown-menu" role="menu" aria-labelledby="drop4">
            <li role="presentation"><a role="menuitem" tabindex="-1" href="#vocal">清真美食广场</a></li>
            <li role="presentation"><a role="menuitem" tabindex="-1" href="#dancing">清真烧烤</a></li>
            <li role="presentation"><a role="menuitem" tabindex="-1" href="#dancing">清真排档</a></li>
          </ul>
        </li>
        <li class="dropdown">
          <a id="drop5" href="#" role="button" class="dropdown-toggle" data-toggle="dropdown">甜点·小食·咖啡馆 <b class="caret"></b></a>
          <ul class="dropdown-menu" role="menu" aria-labelledby="drop5">
            <li role="presentation"><a role="menuitem" tabindex="-1" href="#accounting">甜品店</a></li>
            <li role="presentation"><a role="menuitem" tabindex="-1" href="#computer">咖啡馆</a></li>
          </ul>
        </li>
      </ul>
      <<form class="navbar-search pull-left">
      <input type="text" class="search-query" placeholder="Search">
    </form>
     -->
  </div>
</div>
</div>
<!--news div-->
<br>
<div class="container modules">
  <div class="row-fluid">
    <%= render :partial=>'image_groups' %>
  </div>
</div>

<script type="text/javascript">
$('#edu_slide').unslider({
  fluid: true,
  keys: true,               //  Enable keyboard (left, right) arrow shortcuts
  dots: true
});
</script>

app/views/pub/contact.html.erb
<div class="container" style="height: 600px">
	<h3>地理位置:</h3>
	<hr>
	<%= image_tag "images/location/location.png" %>
	<hr>
	<h3>联系方式</h3>
	<p><strong>公司地址:</strong> 银川市兴庆区南薰中路中房富力城A座809</p>
	<p><strong>联系电话:</strong> 0951-5102315</p>
</div>

app/views/pub/decoration.html.erb
<div class="slide-bar">
  <div class="container">
    <div id="edu_slide" class="banner">
      <ul>
        <li><img src="assets/images/placeholder/1170X300.gif" alt="prod_show" /></li>
        <li><img src="assets/images/placeholder/1170X300.gif" alt="prod_show" /></li>
        <li><img src="assets/images/placeholder/1170X300.gif" alt="prod_show" /></li>
      </ul>
    </div>
  </div>
</div>

<div class="navbar navbar-static-top navbar-inverse" data-spy="affix" data-offset-top="400">
  <div class="navbar-inner">
    <div class="container">
      <a class="brand" href="#">优 · 居</a>
      <a class="brand"><small><em>也许您和您的团队正在创造出让人们生活的更加美好的家具产品，我们时间不足，没有找到您，在此深深道歉。</em></small></a>
      <!-- 
      <ul class="nav">
        <li><a href="#art">趣味艺术品</a></li>
        <li><a href="#man">男人</a></li>        
        <li><a href="#woman">女人</a></li>
        <li><a href="#pet">宠物</a></li>
      </ul>
      <form class="navbar-search pull-left">
      <input type="text" class="search-query" placeholder="Search">
    </form>
    -->
  </div>
</div>
</div>
<!--news div-->
<a href="art"></a>
<br>

<div class="container modules">
  <div class="row-fluid">
    <%= render :partial=>'image_groups' %>
  </div>
</div>

<script type="text/javascript">
$('#edu_slide').unslider({
  fluid: true,
  keys: true,               //  Enable keyboard (left, right) arrow shortcuts
  dots: true
});
</script>

app/views/pub/entertainment.html.erb
<div class="slide-bar">
  <div class="container">
    <div id="edu_slide" class="banner">
      <ul>
        <li><img src="assets/images/entertainment/slide/01.jpg" alt="prod_show" /></li>
      </ul>
    </div>
  </div>
</div>

<div class="navbar navbar-static-top navbar-inverse" data-spy="affix" data-offset-top="400">
  <div class="navbar-inner">
    <div class="container">
      <a class="brand" href="#">优 · 玩</a>
      <a class="brand"><small><em>也许您是个智慧的人或者是能让人放松心情，玩中取乐、知的地方，我们时间不足，没有找到您，在此深深道歉。</em></small></a>
      <!-- 
      <ul class="nav">
        <li><a href="#art">趣味艺术品</a></li>
        <li><a href="#man">男人</a></li>        
        <li><a href="#woman">女人</a></li>
        <li><a href="#pet">宠物</a></li>
      </ul>
      <form class="navbar-search pull-left">
      <input type="text" class="search-query" placeholder="Search">
    </form>
    -->
  </div>
</div>
</div>
<!--news div-->
<a href="art"></a>
<br>

<div class="container modules">
  <div class="row-fluid">
    <%= render :partial=>'image_groups' %>
  </div>
</div>

<script type="text/javascript">
$('#edu_slide').unslider({
  fluid: true,
  keys: true,               //  Enable keyboard (left, right) arrow shortcuts
  dots: true
});
</script>

app/views/pub/index.html.erb
<div class="slide-bar">
  <!--sponsor div-->
  <div class="container">  
    <ul class="thumbnails" style="margin-bottom: 0px;">
      <li class="span3">
        <a href="#" class="thumbnail"><img src="assets/images/spn/spn_ad_1.jpg" alt="spn_show" /></a>
      </li>
      <li class="span3">
        <a href="#" class="thumbnail"><img src="assets/images/spn/spn_ad_2.jpg" alt="spn_show" /></a>
      </li>    
      <li class="span3">
        <a href="#" class="thumbnail"><img src="assets/images/spn/spn_ad_3.jpg" alt="spn_show" /></a>
      </li> 
      <li class="span3">
        <a href="#" class="thumbnail"><img src="assets/images/spn/spn_ad_4.jpg" alt="spn_show" /></a>
      </li>                 
    </ul>
  </div>
  <p class="text-info text-center" style="margin-bottom: 0;"><strong>感谢以上企业对本站的大力支持</strong></p>
</div>      

<!--news div-->

<div id="index_slide" class="banner">
  <ul>
    <li><img src="assets/images/index/slide/01.jpg" alt="prod_show" /></li>
    <li><img src="assets/images/index/slide/02.gif" alt="prod_show" /></li>
  </ul>
</div>
<!--sections-->
<div class="section">
  <div class="container modules">
    <legend><%= link_to "优 · 学", education_path %></legend>
    <div class="row-fluid">
      <ul class="thumbnails">
        <li class="span12">
          <%= link_to image_tag("images/index/edu/01.jpg"), slide_modal_path, class:"thumbnail", remote:true %>
          <!--<a href="#prompt-slide" class="thumbnail" data-toggle="modal" ><img src="images/edu/edu_ad_1.jpg" alt="prod_show" /></a>-->
        </li>
      </ul>
      <ul class="thumbnails">
        <li class="span4">
          <%= link_to image_tag("images/edu/edu_ad_2.jpg"), slide_modal_path, class:"thumbnail", remote:true %>
        </li>
        <li class="span4">
          <%= link_to image_tag("images/edu/edu_ad_3.jpg"), slide_modal_path, class:"thumbnail", remote:true %>
        </li>
        <li class="span4">
          <%= link_to image_tag("images/edu/edu_ad_4.jpg"), slide_modal_path, class:"thumbnail", remote:true %>
        </li>
      </ul>
    </div>
    <p class="pull-right"><em><%= link_to "更多", education_path %></em></p>
    <hr>
  </div>
</div>

<!--sections-->
<div class="section">
  <div class="container modules">
    <legend><%= link_to "优 · 肴", cate_path %></legend>
    <div class="row-fluid">
      <ul class="thumbnails">
        <li class="span12">
          <%= link_to image_tag("images/index/cate/01.jpg"), slide_modal_path, class:"thumbnail", remote:true %>
        </li>
      </ul>
      <ul class="thumbnails">
        <li class="span4">
          <%= link_to image_tag("images/diet/2.jpg"), slide_modal_path, class:"thumbnail", remote:true %>
        </li>
        <li class="span4">
          <%= link_to image_tag("images/diet/3.jpg"), slide_modal_path, class:"thumbnail", remote:true %>
        </li>
        <li class="span4">
          <%= link_to image_tag("images/diet/4.jpg"), slide_modal_path, class:"thumbnail", remote:true %>
        </li>
      </ul>
    </div>
    <p class="pull-right"><em><%= link_to "更多", cate_path %></em></p>
    <hr>
  </div>
</div>

<!--sections-->
<div class="section">
  <div class="container modules">
    <legend><%= link_to "优 · 游", tour_path %></legend>
    <div class="row-fluid">
      <ul class="thumbnails">
        <li class="span12">
          <%= link_to image_tag("images/travel/1.jpg"), slide_modal_path, class:"thumbnail", remote:true %>
        </li>
      </ul>
      <ul class="thumbnails">
        <li class="span4">
          <%= link_to image_tag("images/travel/2.jpg"), slide_modal_path, class:"thumbnail", remote:true %>
        </li>
        <li class="span4">
          <%= link_to image_tag("images/travel/3.jpg"), slide_modal_path, class:"thumbnail", remote:true %>
        </li>
        <li class="span4">
          <%= link_to image_tag("images/travel/4.jpg"), slide_modal_path, class:"thumbnail", remote:true %>
        </li>
      </ul>
    </div>
    <p class="pull-right"><em><%= link_to "更多", tour_path %></em></p>
    <hr>
  </div>
</div>

<!--sections-->
<div class="section">
  <div class="container modules">
    <legend><%= link_to "优 · 美", beauty_path %></legend>
    <div class="row-fluid">
      <ul class="thumbnails">
        <li class="span12">
          <%= link_to image_tag("images/index/beauty/01.jpg"), slide_modal_path, class:"thumbnail", remote:true %>
        </li>
      </ul>
      <ul class="thumbnails">
        <li class="span4">
          <%= link_to image_tag("images/health/2.jpg"), slide_modal_path, class:"thumbnail", remote:true %>
        </li>
        <li class="span4">
          <%= link_to image_tag("images/health/3.jpg"), slide_modal_path, class:"thumbnail", remote:true %>
        </li>
        <li class="span4">
          <%= link_to image_tag("images/health/4.jpg"), slide_modal_path, class:"thumbnail", remote:true %>
        </li>
      </ul>
    </div>
    <p class="pull-right"><em><%= link_to "更多", beauty_path %></em></p>
    <hr>
  </div>
</div>

<!--sections-->
<div class="section">
  <div class="container modules">
    <legend><%= link_to "优 · 品", fab_path %></legend>
    <div class="row-fluid">
      <ul class="thumbnails">
        <li class="span12">
          <%= link_to image_tag("images/onlineshop/1.jpg"), slide_modal_path, class:"thumbnail", remote:true %>
        </li>
      </ul>
      <ul class="thumbnails">
        <li class="span4">
          <%= link_to image_tag("images/onlineshop/2.jpg"), slide_modal_path, class:"thumbnail", remote:true %>
        </li>
        <li class="span4">
          <%= link_to image_tag("images/onlineshop/3.jpg"), slide_modal_path, class:"thumbnail", remote:true %>
        </li>
        <li class="span4">
          <%= link_to image_tag("images/onlineshop/4.jpg"), slide_modal_path, class:"thumbnail", remote:true %>
        </li>
      </ul>
    </div>
    <p class="pull-right"><em><%= link_to "更多", fab_path %></em></p>
    <hr>
  </div>
</div>



<!--sections-->
<div class="section">
  <div class="container modules">
    <legend><%= link_to "优 · 秀", show_path %></legend>
    <div class="row-fluid">
      <ul class="thumbnails">
        <li class="span12">
          <%= link_to image_tag("images/witness/1.jpg"), slide_modal_path, class:"thumbnail", remote:true %>
        </li>
      </ul>
      <% if !@gc['优 · 秀'].nil? %>
          <!-- get the image_groups -->
          <% @groups = @gc['优 · 秀'] %>
          <%= render :partial=>'image_groups' %>
      <% end %>    
    </div>
    <p class="pull-right"><em><%= link_to "更多", show_path %></em></p>
    <hr>
  </div>
</div>

<!--sections-->
<div class="section">
  <div class="container modules">
    <legend><%= link_to "优 · 居", decoration_path %></legend>
    <div class="row-fluid">
      <ul class="thumbnails">
        <li class="span12">
          <%= link_to image_tag("images/house/1.jpg"), slide_modal_path, class:"thumbnail", remote:true %>
        </li>
      </ul>
      <ul class="thumbnails">
        <li class="span4">
          <%= link_to image_tag("images/house/2.jpg"), slide_modal_path, class:"thumbnail", remote:true %>
        </li>
        <li class="span4">
          <%= link_to image_tag("images/house/3.jpg"), slide_modal_path, class:"thumbnail", remote:true %>
        </li>
        <li class="span4">
          <%= link_to image_tag("images/house/4.jpg"), slide_modal_path, class:"thumbnail", remote:true %>
        </li>
      </ul>
    </div>
    <p class="pull-right"><em><%= link_to "更多", decoration_path %></em></p>
    <hr>
  </div>
</div>


<!--sections-->
<div class="section">
  <div class="container modules">
   <legend><%= link_to "优 · 惠", promotion_path %></legend>
   <div class="row-fluid">
    <% if !@gc['优 · 惠'].nil? %>
    <!-- get the image_groups -->
    <% @groups = @gc['优 · 惠'] %>
    <%= render :partial=>'image_groups' %>
    <% end %> 
  </div>
</div>
<p class="pull-right"><em><%= link_to "更多", promotion_path %></em></p>
<hr>
</div>
</div>

<script type="text/javascript">
$('#index_slide').unslider({
  fluid: true,
  keys: true,               //  Enable keyboard (left, right) arrow shortcuts
  dots: true
});
</script>

app/views/pub/promotion.html.erb
<div class="slide-bar">
  <div class="container">
    <div id="edu_slide" class="banner">
      <ul>
        <li><img src="assets/images/promotion/slide/01.jpg" alt="prod_show" /></li>
      </ul>
    </div>
  </div>
</div>

<div class="navbar navbar-static-top navbar-inverse" data-spy="affix" data-offset-top="400">
  <div class="navbar-inner">
    <div class="container">
      <a class="brand" href="#">优 · 惠</a>
      <a class="brand"><small><em>也许您或者一些有责任感的企业，做了很多的好事，我们时间不足，没有发现您们，在此深深道歉。</em></small></a>
      <!-- 
      <ul class="nav">
        <li><a href="#art">趣味艺术品</a></li>
        <li><a href="#man">男人</a></li>        
        <li><a href="#woman">女人</a></li>
        <li><a href="#pet">宠物</a></li>
      </ul>
      <form class="navbar-search pull-left">
        <input type="text" class="search-query" placeholder="Search">
      </form>
       -->
  </div>
</div>
</div>
<!--news div-->
<a href="art"></a>
<br>

<div class="container modules">
  <div class="row-fluid">
    <%= render :partial=>'image_groups' %>
  </div>
</div>

<script type="text/javascript">
$('#edu_slide').unslider({
  fluid: true,
  keys: true,               //  Enable keyboard (left, right) arrow shortcuts
  dots: true
});
</script>

app/views/pub/recruit.html.erb
<div class="container" style="height: 600px">
	<h3>招聘信息</h3>
	目前公司有以下职位虚位以待
	<table class="table table-hover">
		<thead>
			<tr>
				<th style="width: 100px">职位名称</th><th style="width: 80px">工作地点</th><th>职位简要描述</th><th>职位要求</th>
			</tr>
		</thead>
		<tbody class=":nth-child">
			<tr>
				<td>web前端开发工程师</td><td>银川</td><td>负责web前端开发，主要包括页面布局，UI，图片，美工的工作</td><td>熟练掌握CSS， HTML,HTML5, Javascript, jQuery</td>
			</tr>
			<tr>
				<td>后端开发工程师</td><td>银川</td><td>负责后端程序开发，主要构件网站主体架构功能，外部接口，数据库规划设计等</td><td>正规高校计算机专业毕业，熟练掌握关系数据库，有过网站后端开发经验，有Java, C, C#，.net任何一种面向对象语言的开发经验即可，有Ruby开发经验者优先。有ROR开发经验者优先</td>
			</tr>
			<tr><td>客服销售人员</td><td>银川</td><td>负责前后期商户洽谈工作，吸引商户入驻</td><td>销售经验2年以上，沟通能力强，能快速融入团队合作</td></tr>
		</tbody>		
	</table>
	<br>
	<h3>招聘联系方式</h3>
	<p>电话: 0951-5102315</p>
	<p>email: boyishwei@gmail.com</p>
</div>

app/views/pub/show.html.erb
<div class="slide-bar">
  <div class="container">
    <div id="edu_slide" class="banner">
      <ul>
        <li><img src="assets/images/show/slide/01.jpg" alt="prod_show" /></li>
        <li><img src="assets/images/show/slide/02.jpg" alt="prod_show" /></li>
      </ul>
    </div>
  </div>
</div>

<div class="navbar navbar-static-top navbar-inverse" data-spy="affix" data-offset-top="400">
  <div class="navbar-inner">
    <div class="container">
      <a class="brand" href="#">优 · 秀</a>
      <a class="brand"><small><em>朋友是一辈子的财富，真的，真的。</em></small></a>
      <!-- 
      <ul class="nav">
        <li><a href="#art">趣味艺术品</a></li>
        <li><a href="#man">男人</a></li>        
        <li><a href="#woman">女人</a></li>
        <li><a href="#pet">宠物</a></li>
      </ul>
      <form class="navbar-search pull-left">
      <input type="text" class="search-query" placeholder="Search">
    </form>
    -->
  </div>
</div>
</div>
<br>

<div class="container modules">
  <div class="row-fluid">
    <%= render :partial=>'image_groups' %>
  </div>
</div>

<script type="text/javascript">
$('#edu_slide').unslider({
  fluid: true,
  keys: true,               //  Enable keyboard (left, right) arrow shortcuts
  dots: true
});
</script>

app/views/pub/showSlideModal.js.erb
var carousel_html = "<div class='carousel-inner item-detector'>";
var comments_html = "";
<% @images.each do |image| %>
	carousel_html += "	<div class='item pics'>";
	carousel_html += "		<input class='image_id' type='hidden' value='<%= image.id %>'>";	
	carousel_html += "		<img src='<%= j asset_path (image.instance.url || image.location) %>'>";
	carousel_html += "		<div class='carousel-caption caption'><p><%= image.desc %></p></div>";
	carousel_html += "	</div>";
<% end %>
carousel_html += "</div>";
carousel_html += "<a class='carousel-control3 left' href='#image_group_carousel' data-slide='prev'></a>";
carousel_html += "<a class='carousel-control3 right' href='#image_group_carousel' data-slide='next'></a>";
//carousel_html += "<%= link_to 'swich_comments', 'comments/', method: :show, remote:true, class:'btn hide' %>";
$("#image_group_carousel").html(carousel_html);
$("#image_group_carousel").find(".item:first").addClass("active");
//$("#image_group_carousel").carousel('pause');

$("#comments_area").html("<%= j render partial:'comments/show' %>");

$("#slide_modal").modal("show"); 