config/routes.rb
Nyweb::Application.routes.draw do
  get "password_resets/new"

  get "password_resets/edit"

  get "password_resets/update"

  resources :image_groups

  resources :images
  resources :comments, :only => [:create, :destroy, :show]

  resources :users#, :only => [:show, :update,:edit]
  resources :sessions, :only => [:new, :create, :destroy]
  resources :messages, :only => [:index, :new, :create, :show, :destroy]
  resources :password_resets

  get "pub/index"

  root to: 'pub#index'  
  match "/about" => "pub#about"
  match "/contact" => "pub#contact"
  match "/recruit" => "pub#recruit"
  match "/ba" => "pub#ba"
  match "/signout" => "sessions#destroy"
  match "/education" => "pub#edu"
  match "/cate" => "pub#cate"
  match "/fab" => "pub#fab"
  match "/tour" => "pub#tour"
  match "/beauty" => "pub#beauty"
  match "/entertainment" => "pub#entertainment"
  match "/show" => "pub#show"
  match "/decoration" => "pub#decoration"
  match "/promotion" => "pub#promotion"

  match "/slide_modal/:id" => "pub#showSlideModal"
  match "/slide_modal" => "pub#showSlideModalFake"

  match "/update_password" => "users#updatePWD"
  match "/update_email" => "users#updateEmail"
  match "/update_address" => "users#updateAddress"
  match "/update_phone" => "users#updatePhone"

  match "/admin" => "admin#index"
  match "/image_select" => "image_groups#image_select"
  match "/gravatar" => "pub#gravatar"

  match "*a" => "pub#render_404"

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>宁优网</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= javascript_include_tag "unslide" %>
  <%= csrf_meta_tags %>
  <meta name="baidu-site-verification" content="MNrqntYb09" />
  <meta name="360-site-verification" content="0add31ef088a57b30f276e99911a0f72" />
</head>
<body style="background-color: #f5f5f5;" data-spy="scroll" data-target="navbar">
  <!--header-->
  <div class="navbar navbar-static-top" style="margin:0px;">
    <div class="navbar-inner">
      <div class="container">
        <!-- .btn-navbar is used as the toggle for collapsed navbar content -->
        <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </a>
        <%= link_to "宁优网", root_path, class:"brand"%>
        <div  class="nav-collapse navbar-responsive-collapse collapse">
          <ul class="nav">
            <li><a href="/education">优 · 学</a></li>
            <li><a href="/cate">优 · 肴</a></li>
            <li><a href="/tour">优 · 游</a></li>
            <li><a href="/beauty">优 · 美</a></li>
            <li><a href="/entertainment">优 · 玩</a></li>
            <li><a href="/fab">优 · 品</a></li>
            <li><a href="/show">优 · 秀</a></li>
            <li><a href="/decoration">优 · 居</a></li>
            <li><a href="/promotion">优 · 惠</a></li>
          </ul>
          <div class="nav pull-right user-zone" id="user_zone">
            <%= render :partial => 'users/login', locals:{ :user=>User.new }%>
          </div>
        </div>
      </div>
    </div>
  </div>
  <!--
  <div style="background-color: #99CC66;">
    <div class="container">
      <div class="row">
        <div class="span6">
          <h3>宁优网 <small>只为好产品代言</small></h3>
        </div>
        
      </div>
    </div>
  </div>-->
  <!--nav-bar-->

  <%= yield %> 

  <!-- Modal -->
  <div id="slide_modal" class="advanced-modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
      <h3 id="myModalLabel">&nbsp;</h3>
    </div>
    <div class="modal-body">
      <div id="image_group_carousel" class="carousel slide" data-ride="carousel">
      </div>
      <%= link_to 'switch', 'comments/',  method: :get, remote:true, id:"hidden_switch", class:'btn hide' %>
      <div class="row">
        <div class="span5">
          <div id="comments_area" class="well well-nomargin">
          </div>
        </div>

        <div class="span3">
          <div id="explanation" class="alert alert-error hide fade in">
            <button type="button" class="close close-btn">&times;</button>
            <p id="error_msg"></p>
          </div>
          <%= form_for(Comment.new, url:comments_path, remote:true) do |c| %>
          <%= c.text_area :comment , id:"comment_area", rows: 3%>
          <%= c.hidden_field :image_id %>
          <%= c.submit "发表评论", id:"comment_submit", class:"btn btn-warning" %>
          <% end %>
        </div>
      </div>
    </div>
    <div class="modal-footer">
      <button class="btn" data-dismiss="modal" aria-hidden="true">关闭</button>
    </div>
  </div>

  <!--login modal-->
  <div id="regSucModal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myRegSucLabel" aria-hidden="true">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h3 id="myRegSucLabel" class="text-center">恭喜您, 注册成功!</h3>
    </div>
    <div class="modal-body text-center">
        ^o^
    </div>
    <div class="modal-footer text-center">
        <button class="btn" data-dismiss="modal" aria-hidden="true">关&nbsp;闭</button>
    </div>
  </div>

  <!--footer-->          
  <footer class="footer">
    <div class="container">
      <!--
      <p>
        Designed and build by
        <a href="http://www.boyishwei.com" target="_blank">Ryan Jiang</a>
        & Hao, Zhang
      </p>
      -->
      <p>All rights reserved by Ning Xia Di Guang Technical Comp</p>
      <p>Copyright &copy; 2013 宁夏滴光信息科技有限公司</p>
      <ul class="footer-links">
        <li>
          <%=link_to "关于", about_path%>
        </li>
        <li class="muted"> · </li>
        <li>
          <%=link_to "联系我们", contact_path%>
        </li>
        <li class="muted"> · </li>
        <li>
          <%=link_to "给我们留言", new_message_path%>
        </li>
        <li class="muted"> · </li>
        <li>
          <%=link_to "招聘", recruit_path%>
        </li>
        <li class="muted"> · </li>
        <li>
          <%=link_to "宁ICP备13000608号", ba_path%>
        </li>
        <li>
          <%= javascript_include_tag "add_ons" %>
          <script type="text/javascript">
            var cnzz_protocol = (("https:" == document.location.protocol) ? " https://" : " http://");document.write(unescape("%3Cspan id='cnzz_stat_icon_5736209'%3E%3C/span%3E%3Cscript src='" + cnzz_protocol + "s17.cnzz.com/stat.php%3Fid%3D5736209%26show%3Dpic' type='text/javascript'%3E%3C/script%3E"));
          </script>
        </li>
        <li>
          <script>
          (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
            (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
            m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
          })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

          ga('create', 'UA-46161845-1', '0951good.com');
          ga('send', 'pageview');

          </script>
        </li>
      </ul>
    </div>
  </footer>
</body>
</html>